# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres_a:
    image: postgres-splitbrain
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: example
      NODE_ROLE: PRIMARY
  
  postgres_b:
    image: postgres-splitbrain
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: example
      REPLICATION_HOST: postgres_a
      NODE_ROLE: REPLICA
